apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-user-provisioning-script
data:
  provision-users.sh: |
    #!/bin/bash

    GRAFANA_URL="http://localhost:3000"
    ADMIN_USER=$(cat /secrets/admin-username)
    ADMIN_PASSWORD=$(cat /secrets/admin-password)

    USERS=(
      '{"name": "viewer", "email": "viewer@example.com", "login": "viewer", "password": "viewer123", "role": "Viewer"}'
      '{"name": "editor", "email": "editor@example.com", "login": "editor", "password": "editor123", "role": "Editor"}'
      '{"name": "admin", "email": "admin@example.com", "login": "admin", "password": "admin123", "role": "Admin"}'
    )

    for USER in "${USERS[@]}"; do
      curl -u "$ADMIN_USER:$ADMIN_PASSWORD" -X POST "$GRAFANA_URL/api/admin/users" \
        -H "Content-Type: application/json" \
        -d "$USER"
    done
