apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
data:
  admin-username: YWRtaW4=        # Base64 for "admin"
  admin-password: YWRtaW4xMjM=    # Base64 for "admin123"
