apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
data:
  admin-username: YWRtaW4=        # Base64 for "admin"
  admin-password: YWRtaW4xMjM=    # Base64 for "admin123"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-user-passwords
type: Opaque
data:
  user1-password: cGFzc3dvcmQx   # Base64 for "password1"
  user2-password: cGFzc3dvcmQy   # Base64 for "password2"
  user3-password: cGFzc3dvcmQz   # Base64 for "password3"
  # Add passwords for up to 50 users
