apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-user-provisioning-script
data:
  provision-users.sh: |
    #!/bin/bash

    GRAFANA_URL="http://localhost:3000"
    ADMIN_USER=$(cat /secrets/admin-username)
    ADMIN_PASSWORD=$(cat /secrets/admin-password)

    USER_LIST='[
      {"name": "viewer", "email": "viewer@example.com", "login": "viewer", "password_secret_key": "viewer-password", "role": "Viewer"},
      {"name": "editor", "email": "editor@example.com", "login": "editor", "password_secret_key": "editor-password", "role": "Editor"},
      {"name": "admin", "email": "admin@example.com", "login": "admin", "password_secret_key": "admin-password", "role": "Admin"}
    ]'

    echo "$USER_LIST" | jq -c '.[]' | while read USER; do
      NAME=$(echo $USER | jq -r '.name')
      EMAIL=$(echo $USER | jq -r '.email')
      LOGIN=$(echo $USER | jq -r '.login')
      ROLE=$(echo $USER | jq -r '.role')
      PASSWORD_SECRET_KEY=$(echo $USER | jq -r '.password_secret_key')

      # Fetch the password from the Secret
      PASSWORD=$(cat /secrets/$PASSWORD_SECRET_KEY)

      # Create the user using Grafana API
      curl -u "$ADMIN_USER:$ADMIN_PASSWORD" -X POST "$GRAFANA_URL/api/admin/users" \
        -H "Content-Type: application/json" \
        -d "{\"name\":\"$NAME\",\"email\":\"$EMAIL\",\"login\":\"$LOGIN\",\"password\":\"$PASSWORD\",\"role\":\"$ROLE\"}"
    done
