apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
data:
  admin-username: YWRtaW4=        # Base64 for "admin"
  admin-password: YWRtaW4xMjM=    # Base64 for "admin123"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-user-passwords
type: Opaque
data:
  viewer-password: dmlld2VyMTIz  # Base64 for "viewer123"
  editor-password: ZWRpdG9yMTIz  # Base64 for "editor123"
  admin-password: YWRtaW4xMjM=   # Base64 for "admin123"
